-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 16:31:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema stud_v23_kma150
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema stud_v23_kma150
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `stud_v23_kma150` DEFAULT CHARACTER SET utf8 ;
USE `stud_v23_kma150` ;

-- -----------------------------------------------------
-- Table `stud_v23_kma150`.`quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_kma150`.`quiz` ;

CREATE TABLE IF NOT EXISTS `stud_v23_kma150`.`quiz` (
  `Quiz_ID` INT NOT NULL AUTO_INCREMENT,
  `Quiz_name` VARCHAR(45) NOT NULL,
  `Quiz_description` TEXT NULL DEFAULT '\"\"',
  `Total_questions` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`Quiz_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_kma150`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_kma150`.`question` ;

CREATE TABLE IF NOT EXISTS `stud_v23_kma150`.`question` (
  `Question_ID` INT NOT NULL AUTO_INCREMENT,
  `Question` TEXT NOT NULL,
  `Quiz` INT NOT NULL,
  `Answer1` VARCHAR(45) NOT NULL,
  `Answer2` VARCHAR(45) NOT NULL,
  `Answer3` VARCHAR(45) NOT NULL,
  `Answer4` VARCHAR(45) NOT NULL,
  `Correct_answer` INT NOT NULL,
  PRIMARY KEY (`Question_ID`, `Quiz`),
  INDEX `fk_question_quiz_idx` (`Quiz` ASC) VISIBLE,
  CONSTRAINT `fk_question_quiz`
    FOREIGN KEY (`Quiz`)
    REFERENCES `stud_v23_kma150`.`quiz` (`Quiz_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_kma150`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_kma150`.`user` ;

CREATE TABLE IF NOT EXISTS `stud_v23_kma150`.`user` (
  `User_ID` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(255) NOT NULL,
  `Password` TEXT NOT NULL,
  `Is_admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`User_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `stud_v23_kma150`.`quiz_playthrough`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `stud_v23_kma150`.`quiz_playthrough` ;

CREATE TABLE IF NOT EXISTS `stud_v23_kma150`.`quiz_playthrough` (
  `Playthrough_ID` INT NOT NULL AUTO_INCREMENT,
  `User` INT NOT NULL,
  `Quiz` INT NOT NULL,
  `Score` INT NOT NULL,
  PRIMARY KEY (`Playthrough_ID`, `User`, `Quiz`),
  INDEX `fk_quiz_playthrough_user1_idx` (`User` ASC) VISIBLE,
  INDEX `fk_quiz_playthrough_quiz1_idx` (`Quiz` ASC) VISIBLE,
  CONSTRAINT `fk_quiz_playthrough_user1`
    FOREIGN KEY (`User`)
    REFERENCES `stud_v23_kma150`.`user` (`User_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_quiz_playthrough_quiz1`
    FOREIGN KEY (`Quiz`)
    REFERENCES `stud_v23_kma150`.`quiz` (`Quiz_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
