-- MySQL Script generated by MySQL Workbench
-- Thu May 11 17:15:07 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`questionType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`questionType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`questionType` (
  `questionType_ID` INT NOT NULL,
  `type` VARCHAR(45) NULL,
  PRIMARY KEY (`questionType_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`quiz`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`quiz` ;

CREATE TABLE IF NOT EXISTS `mydb`.`quiz` (
  `quiz_ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `totalQuestions` INT NOT NULL,
  PRIMARY KEY (`quiz_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`question` ;

CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `question_ID` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(255) NOT NULL,
  `questionType` INT NOT NULL,
  `quiz` INT NOT NULL,
  PRIMARY KEY (`question_ID`, `quiz`),
  INDEX `fk_question_questionType_idx` (`questionType` ASC) VISIBLE,
  INDEX `fk_question_quiz1_idx` (`quiz` ASC) VISIBLE,
  CONSTRAINT `fk_question_questionType`
    FOREIGN KEY (`questionType`)
    REFERENCES `mydb`.`questionType` (`questionType_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_question_quiz1`
    FOREIGN KEY (`quiz`)
    REFERENCES `mydb`.`quiz` (`quiz_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` VARCHAR(255) NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  `firstName` VARCHAR(255) NOT NULL,
  `lastName` VARCHAR(255) NOT NULL,
  `password` TEXT NOT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`correctionStatus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`correctionStatus` ;

CREATE TABLE IF NOT EXISTS `mydb`.`correctionStatus` (
  `correctionStatus_ID` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`correctionStatus_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`answer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`answer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`answer` (
  `answer_ID` INT NOT NULL AUTO_INCREMENT,
  `answer` TEXT NOT NULL,
  `question` INT NOT NULL,
  `user` VARCHAR(255) NOT NULL,
  `result` TINYINT NOT NULL,
  `comment` TEXT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`answer_ID`, `question`),
  INDEX `fk_answer_question1_idx` (`question` ASC) VISIBLE,
  INDEX `fk_answer_user1_idx` (`user` ASC) VISIBLE,
  INDEX `fk_answer_correctionStatus1_idx` (`status` ASC) VISIBLE,
  CONSTRAINT `fk_answer_question1`
    FOREIGN KEY (`question`)
    REFERENCES `mydb`.`question` (`question_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_user1`
    FOREIGN KEY (`user`)
    REFERENCES `mydb`.`user` (`username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_answer_correctionStatus1`
    FOREIGN KEY (`status`)
    REFERENCES `mydb`.`correctionStatus` (`correctionStatus_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`choices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`choices` ;

CREATE TABLE IF NOT EXISTS `mydb`.`choices` (
  `choices_ID` INT NOT NULL,
  `choice1` VARCHAR(255) NOT NULL,
  `choice2` VARCHAR(255) NOT NULL,
  `choice3` VARCHAR(255) NOT NULL,
  `choice4` VARCHAR(255) NOT NULL,
  `question_question_ID` INT NOT NULL,
  `question_quiz` INT NOT NULL,
  PRIMARY KEY (`choices_ID`),
  INDEX `fk_choices_question1_idx` (`question_question_ID` ASC, `question_quiz` ASC) VISIBLE,
  CONSTRAINT `fk_choices_question1`
    FOREIGN KEY (`question_question_ID` , `question_quiz`)
    REFERENCES `mydb`.`question` (`question_ID` , `quiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
